
import React from 'react';
import { ClipboardList, Play, Trash2, X, Printer } from 'lucide-react';
import { CartItem, UnitOfMeasure, AppConfig } from '../types';

interface HeldCartsModalProps {
  isOpen: boolean;
  onClose: () => void;
  heldCarts: CartItem[][];
  onResume: (index: number) => void;
  onDelete: (index: number) => void;
  isDarkMode: boolean;
  config: AppConfig;
}

const HeldCartsModal: React.FC<HeldCartsModalProps> = ({
  isOpen,
  onClose,
  heldCarts,
  onResume,
  onDelete,
  isDarkMode,
  config,
}) => {
  if (!isOpen) return null;

  const calculateCartTotal = (cart: CartItem[]) => {
    const subtotal = cart.reduce((acc, item) => {
      const price = item.product.uom === UnitOfMeasure.KG
        ? item.product.price * (item.weight || 1)
        : item.product.price * item.quantity;
      return acc + price;
    }, 0);
    const tax = subtotal * config.taxRate;
    return subtotal + tax;
  };

  const handlePrintHeldCarts = () => {
    const printContent = `
      <div class="p-8 font-sans">
        <div class="text-center mb-6">
          <h1 class="text-2xl font-bold">Held Transactions Summary</h1>
          <p class="text-sm text-gray-500">${new Date().toLocaleString()}</p>
        </div>
        <div class="space-y-4">
          ${heldCarts.map((cart, index) => `
            <div class="p-4 border rounded-lg">
              <div class="flex justify-between items-center">
                <div>
                  <h2 class="font-bold text-lg">Order #${index + 1}</h2>
                  <p class="text-sm text-gray-600">${cart.length} items</p>
                </div>
                <div class="font-bold text-lg">${config.currencySymbol}${calculateCartTotal(cart).toFixed(2)}</div>
              </div>
            </div>
          `).join('')}
        </div>
        <div class="text-center mt-8 text-xs text-gray-400">
          <p>Generated by ${config.storeName} POS</p>
        </div>
      </div>
    `;

    const printWindow = window.open('', '_blank', 'width=800,height=600');
    if (!printWindow) {
      alert('Please allow popups to print held transactions.');
      return;
    }

    printWindow.document.write(`
        <html>
            <head>
                <title>Held Transactions Summary</title>
                <script src="https://cdn.tailwindcss.com"></script>
                <style>
                    body { background: white; -webkit-print-color-adjust: exact; }
                </style>
            </head>
            <body>
                ${printContent}
                <script>
                    window.onload = () => {
                        setTimeout(() => {
                            window.focus();
                            window.print();
                            window.close();
                        }, 500);
                    };
                </script>
            </body>
        </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 animate-in fade-in duration-300">
      <div className={`w-full max-w-lg rounded-3xl shadow-2xl flex flex-col ${isDarkMode ? 'bg-slate-800' : 'bg-white'}`}>
        <div className={`flex justify-between items-center p-6 border-b ${isDarkMode ? 'border-slate-700' : 'border-slate-100'}`}>
          <div className="flex items-center gap-3">
            <ClipboardList className="text-amber-500" size={24} />
            <h2 className="text-xl font-black">Held Transactions</h2>
          </div>
          <button onClick={onClose} className={`p-2 rounded-full ${isDarkMode ? 'hover:bg-slate-700' : 'hover:bg-slate-100'}`}>
            <X size={20} />
          </button>
        </div>
        
        <div className="flex-1 p-6 space-y-4 overflow-auto max-h-[60vh]">
          {heldCarts.length === 0 ? (
            <div className="text-center py-12 text-slate-500 flex flex-col items-center">
              <div className={`relative w-24 h-24 mb-6 flex items-center justify-center rounded-full ${isDarkMode ? 'bg-slate-700' : 'bg-slate-100'}`}>
                  <ClipboardList size={48} className={`${isDarkMode ? 'text-slate-500' : 'text-slate-400'}`} />
              </div>
              <h3 className={`font-bold text-xl mb-2 ${isDarkMode ? 'text-slate-200' : 'text-slate-700'}`}>No Held Carts</h3>
              <p className="text-sm text-slate-500 max-w-xs">
                  When you hold a transaction, you can find it here to resume later.
              </p>
            </div>
          ) : (
            heldCarts.map((cart, index) => (
              <div key={index} className={`p-4 rounded-2xl flex items-center justify-between transition-colors ${isDarkMode ? 'bg-slate-700' : 'bg-slate-50'}`}>
                <div>
                  <p className="font-bold">Order #{index + 1}</p>
                  <p className="text-sm text-slate-500">{cart.length} items - <span className="font-semibold">{config.currencySymbol}{calculateCartTotal(cart).toFixed(2)}</span></p>
                </div>
                <div className="flex items-center gap-2">
                  <button 
                    onClick={() => onDelete(index)}
                    className={`p-3 rounded-xl text-rose-500 transition-colors ${isDarkMode ? 'hover:bg-rose-500/10' : 'hover:bg-rose-100'}`}
                    aria-label="Delete"
                  >
                    <Trash2 size={18} />
                  </button>
                  <button 
                    onClick={() => onResume(index)}
                    className="flex items-center gap-2 px-4 py-3 rounded-xl bg-emerald-600 text-white font-bold hover:bg-emerald-700 transition-colors"
                  >
                    <Play size={16} /> Resume
                  </button>
                </div>
              </div>
            ))
          )}
        </div>
        
        {heldCarts.length > 0 && (
          <div className={`p-6 border-t ${isDarkMode ? 'border-slate-700' : 'border-slate-100'} flex justify-end`}>
            <button
              onClick={handlePrintHeldCarts}
              className="flex items-center justify-center gap-2 py-3 px-6 rounded-2xl bg-slate-700 text-white font-bold hover:bg-slate-800 transition-colors"
            >
              <Printer size={18} /> Print Held Carts
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default HeldCartsModal;
